# Hexiang Zhang

## Understanding Concepts Questions

  1. Git is the tools that help us with version controlling. Git is what allows us to add, commit, push, pull, etc. Github is the online remote service that holds our projects managed by git. We can use git to push out code to Github.
  
  2. I mean they could be used independently. It just wouldn't be as effective. You could just do everything by using the buttons on GitHub and transporting your code may be difficult, but it's nice to have git too to go quicker. You can't really share projects with other people easily if you just use Git without GitHub. You could still manage your own code with git. Github helps with saving code remotely. We can used them together so that code can be shared and saved remotely. We can continue to work as normal and use Git to send our code to GitHub and have it manage our project.    
  
  3. A repository in Git is like a regular folder that has git setup to monitor. 
      1. mkdir folder_name
      2. cd folder_name
      3. git init 
  
## Coding Exercises
```{r}
# 1. Write code to count the total number of NA occurrences in the vector 
X <- c(47,34,33,65,37,NA,43,NA,11,NA,23,NA) 
sum(is.na(X))

# 2. Run the following code:
age = c(25,30,45,60,12,41)
smoker = c('T','F','T','F','F','F')
weight = c(120,137,0,168,91,142)

# Change weight from 0 to 150.
weight[3] <- 150

example_data = data.frame(age,smoker,weight)
example_data   
   
# 3. In the following I have two code snippets. Turn these code snippets into functions. Think about what each function does and what you would name it. How many arguments does it need?
mean(is.na(X))

# Percentage of vector x that is NA. Takes 1 vector as argument.
na_percentage <- function(vec) {
  x <- sum(is.na(vec))
  return(x / length(vec))
}
na_percentage(X)

X / sum(X, na.rm = TRUE)

# Divide each element of vector x with the total sum all all the elements (excluding NA). Percentage of each element in the vector. Takes 1 vector as arguement. 
count_to_percentage <- function(vec) {
  vec2 <- vec[-which(is.na(vec))]
  total <- sum(vec2)
  return(vec/total)
}
count_to_percentage(X)

# 4. Write a function named both_na(). This function take two vectors of the same length and returns the number of positions that have an NA value in both vectors.

both_na <- function(vec1, vec2) {
  return(sum(is.na(vec1)) + sum(is.na(vec2)))
}
both_na(X, X)
```